trigger:
  - master

pool: MyAgent

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: npm install
    displayName: 'Install dependencies'

  - script: npm run lib:pack
    displayName: 'Build package'

  - script: npm pack
    displayName: 'Pack package'

  - task: CopyFiles@2
    inputs:
      Contents: '*.tgz'
      TargetFolder: $(Build.ArtifactStagingDirectory)
    displayName: 'Copy archives to artifacts staging directory'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      ArtifactName: 'Package'
    displayName: 'Publish artifacts'
