trigger:
- master

pool: MyAgent

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: DownloadSecureFile@1
  name: envFile
  displayName: 'Download env file'
  inputs:
    secureFile: '.env'

- task: CopyFiles@2
  inputs:
    Contents: '$(envFile.secureFilePath)/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy env file to artifacts staging directory'

- script: npm install
  displayName: 'npm install'

- script: npm run build
  displayName: 'npm run build'

- task: CopyFiles@2
  inputs:
    Contents: 'build/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy files to artifacts staging directory'

- task: PublishBuildArtifacts@1
  inputs: 
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: 'drop'
  displayName: 'Publish artifacts'